FROM php:8.4-cli

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git=1:2.* \
    curl=7.* \
    libpng-dev=1.6.* \
    libonig-dev=6.* \
    libxml2-dev=2.9.* \
    zip=3.* \
    unzip=6.* \
    nodejs=18.* \
    npm=9.* \
    libzip-dev=1.* \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy existing application directory contents
COPY . /var/www/html

# Set permissions and install dependencies
RUN git config --global --add safe.directory /var/www/html \
    && chown -R www-data:www-data /var/www/html \
    && composer install --no-interaction --optimize-autoloader \
    && npm install \
    && npm run build

# Expose port 8000
EXPOSE 8000

# Start Laravel server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
