name: Laravel CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

# Add permissions configuration for GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  laravel-tests:
    name: Laravel CI
    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@2.33.0
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install NPM Dependencies
      run: npm ci
      
    - name: Build Frontend Assets
      run: npm run build

    - name: Verify application structure
      run: |
        # Check if key files and directories exist
        echo "Checking application structure..."
        [ -d "app" ] && echo "✓ app directory exists" || echo "✗ app directory missing"
        [ -d "config" ] && echo "✓ config directory exists" || echo "✗ config directory missing"
        [ -d "public" ] && echo "✓ public directory exists" || echo "✗ public directory missing"
        [ -d "resources" ] && echo "✓ resources directory exists" || echo "✗ resources directory missing"
        [ -d "routes" ] && echo "✓ routes directory exists" || echo "✗ routes directory missing"
        [ -f "artisan" ] && echo "✓ artisan exists" || echo "✗ artisan missing"
        [ -f "composer.json" ] && echo "✓ composer.json exists" || echo "✗ composer.json missing"
        
        # Check front-end build output
        [ -d "public/build" ] && echo "✓ Frontend assets built successfully" || echo "✗ Frontend build failed"

    - name: Run code quality checks
      run: |
        # Run any custom code quality tools here
        vendor/bin/phpstan analyze app --level=5 || true
        
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: laravel-tests
    # Only run on push to main/master branch, not pull requests
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max