name: Laravel Testing

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  dusk-tests:
    name: Laravel Testing
    runs-on: ubuntu-latest
    
    services:
      # If your application uses MySQL
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: finance_test
          MYSQL_USER: finance_user
          MYSQL_PASSWORD: finance_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@2.33.0
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo, mysql, pdo, pdo_mysql
        tools: composer:v2
        coverage: xdebug
    
    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    
    - name: Generate key
      run: cp .env.example .env && php artisan key:generate
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install npm dependencies
      run: npm ci || npm install
    
    - name: Build assets
      run: npm run build
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache database
      
    - name: Run Migrations with seed
      run: php artisan migrate:fresh --seed

    - name: Execute PHPUnit tests (Unit and Feature tests)
      run: vendor/bin/phpunit
      
    - name: Run PHPStan
      run: vendor/bin/phpstan analyze app --level=5 || true
    
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver --detect
    
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux &
      
    - name: Wait for Chrome Driver
      run: sleep 5
    
    - name: Start Laravel Server for Dusk
      run: |
        php -d variables_order=EGPCS -S 127.0.0.1:8000 -t public &
        sleep 5
        curl -s -I http://127.0.0.1:8000 || echo "Server not responding yet"
    
    - name: Run Dusk Tests
      env:
        CI: true
      run: |
        # Show server output for debugging
        curl -s http://127.0.0.1:8000 > /tmp/homepage.html
        echo "Homepage Content Length: $(wc -l < /tmp/homepage.html)"
        
        # Run tests with increased memory
        php -d memory_limit=512M artisan dusk --verbose
    
    - name: Capture logs on failure
      if: failure()
      run: |
        echo "===== Laravel Logs ====="
        tail -n 100 storage/logs/laravel*.log || true
        
        # Dump database content for debugging
        echo "===== Database Content ====="
        php artisan tinker --execute="DB::connection('sqlite')->table('users')->get();" || true
        
        # Check if server is still running
        echo "===== Server Status ====="
        curl -v http://127.0.0.1:8000 || true
    
    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: tests/Browser/screenshots
    
    - name: Upload Console Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: console-logs
        path: tests/Browser/console
